# Use the official Python 3.12 image from Docker Hub
FROM python:3.12

# Create a non-root user with sudo access
RUN useradd -m user && echo "user:user" | chpasswd && adduser user sudo

# Install sudo and curl
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y sudo curl graphviz libgraphviz-dev

# Allow the user to use sudo without a password
RUN echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Install Zsh
RUN apt-get install -y zsh

# Install fzf (fuzzy finder)
RUN sudo apt install fzf

# Install Zoxide
RUN sudo apt install -y zoxide 

# Set Zsh as the default shell
SHELL ["/bin/zsh", "-c"]

# Switch to the new user
USER user

# Set the working directory
WORKDIR /home/user/{{cookiecutter.project_name}}

# Change the ownership of the workdir to the user
RUN chown -R user:user /home/user/{{cookiecutter.project_name}}

# create a .ssh directory for the user and set the permissions
RUN mkdir -p /home/user/.ssh
RUN sudo chown -R user:user /home/user/.ssh && chmod 700 /home/user/.ssh

# Install Oh My Zsh for user
RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" && \
    sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="robbyrussell"/g' ~/.zshrc

# Update pip
RUN pip install --upgrade pip

# Create a virtual environment and activate it in terminals
RUN python -m venv ~/venv && echo "source ~/venv/bin/activate" >> ~/.zshrc

# Install Zoxide in the shell
RUN zoxide init zsh > /tmp/zoxide_init.zsh
RUN echo "source /tmp/zoxide_init.zsh" >> ~/.zshrc

# Install Python libraries from requirements.txt
COPY ../{{cookiecutter.library_name}}/requirements.txt .
RUN ~/venv/bin/pip install -r requirements.txt

# Preload commands into the shell's history
RUN echo 'cd /home/user/{{cookiecutter.project_name}}/{{cookiecutter.library_name}} && flit install -s --python $(which python)' >> ~/.zsh_history
RUN echo 'ssh -T git@github.com' >> ~/.zsh_history